# Generated by Django 4.2.4 on 2025-02-24 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.buildingtype')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purity', models.CharField(choices=[('Impure', 'Impure'), ('Normal', 'Normal'), ('Pure', 'Pure')], max_length=10)),
                ('clock_speed', models.FloatField(default=100.0)),
                ('base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='production.base')),
                ('miner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.minertype')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.resourcetype')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('item_type', models.CharField(choices=[('input', 'Input'), ('output', 'Output')], max_length=6)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.recipe')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.resourcetype')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_speed', models.FloatField(default=100.0)),
                ('is_active', models.BooleanField(default=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='production.base')),
                ('facility_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.buildingtype')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.recipe')),
            ],
        ),
    ]
